# Generated by Django 3.0.6 on 2020-05-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'farmacia',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bula', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologia', models.CharField(max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('seed', models.CharField(max_length=256)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Medicamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Paciente')),
            ],
            options={
                'db_table': 'receita',
            },
        ),
    ]
