# Generated by Django 3.0.6 on 2020-05-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='signature',
        ),
    ]
